version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_graphql_tutorial
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: graphql-tutorial
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
