version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_graphql_tutorial
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: graphql-tutorial
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      TZ: UTC
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+00:00' # Set default timezone to UTC

  oracle:
    image: registry.sgts.gitlab-dedicated.com/wog/mom/wins/wins-po/app-wp/intranet-data-layer/oracle/database:19.3.0-ee-slim-faststart
    container_name: test_oracle_db
    environment:
      - ORACLE_DATABASE=ORCLPDB1
      - ORACLE_PASSWORD=testuser
      - TZ=Asia/Singapore
    volumes:
      - ./database/scripts:/container-entrypoint-initdb.d
    ports:
      - '127.0.0.1:1522:1521'
      - '127.0.0.1:5507:5500'

volumes:
  mysql_data:
